apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-resources
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/T2Dzung/coffee-shop.git
    targetRevision: feat/k3s-ha
    path: infrastructure/k8s/gitops/addons/longhorn/resources
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy: {}
