apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-ownership-guard
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/T2Dzung/coffee-shop.git
    targetRevision: feat/k3s-ha
    path: platform-ownership-guard/config/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-ownership-guard-system
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /status/terminatingReplicas
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
