apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../default
- ../observability
- ../samples

patches:
- patch: |-
    - op: replace
      path: /metadata/namespace
      value: coffeeshop
  target:
    group: guard.platform.t2dzung.github.io
    kind: OwnershipAudit
    name: coffeeshop-ownership
    version: v1alpha1

images:
- digest: sha256:98cfcb1c13d0cce096beb688fba6c9ab007954ee8a9cede5b8c66e1ec0c2e4f1
  name: controller
  newName: 423623841278.dkr.ecr.ap-southeast-1.amazonaws.com/platform-ownership-guard
