apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: coffeeshop-secret
  namespace: coffeeshop
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: coffeeshop-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /coffeeshop/prod/application
