apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: coffeeshop-rabbitmq-default-user
  namespace: coffeeshop
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: coffeeshop-rabbitmq-default-user
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: /coffeeshop/prod/application
        property: RABBITMQ_DEFAULT_USER
    - secretKey: password
      remoteRef:
        key: /coffeeshop/prod/application
        property: RABBITMQ_DEFAULT_PASS
    - secretKey: default_user.conf
      remoteRef:
        key: /coffeeshop/prod/application
        property: RABBITMQ_DEFAULT_USER_CONFIG
