apiVersion: v1
kind: PersistentVolume
metadata:
  name: go-modules-cache-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/go-cache
    server: 172.31.28.92 # Internal IP of the Primary node acting as NFS Server
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: go-modules-cache-pvc
  namespace: dev-ci
spec:
  storageClassName: "" # Empty to bind directly with the static PV above
  volumeName: go-modules-cache-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
