apiVersion: platform.t2dzung.github.io/v1alpha1
kind: CoffeeShopService
metadata:
  name: barista
  namespace: coffeeshop
spec:
  managementPolicy: Observe
  image:
    repository: 423623841278.dkr.ecr.ap-southeast-1.amazonaws.com/go-coffeeshop-barista
    tag: 9865dddfa41bac06413e3266a1818a2f344cc193
  replicas: 1
  service:
    enabled: false
  env:
    - name: POSTGRES_DB
      valueFrom:
        configMapKeyRef:
          name: coffeeshop-config
          key: POSTGRES_DB
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: coffeeshop-secret
          key: POSTGRES_PASSWORD
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 128Mi
  networkPolicy:
    enabled: false
