apiVersion: platform.t2dzung.github.io/v1alpha1
kind: CoffeeShopService
metadata:
  name: proxy
  namespace: coffeeshop
spec:
  managementPolicy: Observe
  image:
    repository: 423623841278.dkr.ecr.ap-southeast-1.amazonaws.com/go-coffeeshop-proxy
    tag: 9865dddfa41bac06413e3266a1818a2f344cc193
  replicas: 2
  ports:
    - name: http
      containerPort: 5000
  service:
    enabled: true
    ports:
      - name: http
        port: 5000
        targetPort: http
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 128Mi
  probes:
    readiness:
      tcpSocket:
        port: http
      periodSeconds: 5
    liveness:
      tcpSocket:
        port: http
      periodSeconds: 10
  networkPolicy:
    enabled: true
    egress:
      - service: product
        port: 5001
      - service: counter
        port: 5002
