apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: go-modules-cache-longhorn-pvc
  namespace: dev-ci
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-rwx
  resources:
    requests:
      storage: 10Gi
