apiVersion: v1
kind: ResourceQuota
metadata:
  name: runner-compute-quota
  namespace: dev-ci
spec:
  hard:
    pods: "10"
    requests.cpu: "6"
    requests.memory: 10Gi
    limits.cpu: "24"
    limits.memory: 28Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: runner-container-limits
  namespace: dev-ci
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      default:
        cpu: "2"
        memory: 2Gi
      max:
        cpu: "4"
        memory: 4Gi
