FROM gcr.io/distroless/static-debian12:nonroot

# Copy configuration, migrations and the pre-built binary directly from the host workspace
COPY ./cmd/kitchen/config.yml /config.yml
COPY ./db/migrations /db/migrations
COPY ./bin/kitchen /app

ENTRYPOINT ["/app"]