FROM gcr.io/distroless/static-debian12:nonroot

EXPOSE 5002

# Copy configuration, migrations and the pre-built binary directly from the host workspace
COPY ./cmd/counter/config.yml /config.yml
COPY ./db/migrations /db/migrations
COPY ./bin/counter /app

ENTRYPOINT ["/app"]