FROM gcr.io/distroless/static-debian12:nonroot

EXPOSE 5000

# Copy configuration and the pre-built binary directly from the host workspace
COPY ./cmd/proxy/config.yml /config.yml
COPY ./bin/proxy /app

ENTRYPOINT ["/app"]