FROM gcr.io/distroless/static-debian12:nonroot

WORKDIR /app

EXPOSE 5001

# Copy configuration and the pre-built binary directly from the host workspace
COPY ./cmd/product/config.yml ./config.yml
COPY ./bin/product ./app-service

ENTRYPOINT ["./app-service"]