# Step 1: Builder
FROM golang:1.24-alpine AS builder

WORKDIR /app

RUN apk add --no-cache git ca-certificates tzdata

# Cache dependencies
COPY go.mod go.sum ./
RUN go mod download

# Build application
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -tags migrate -ldflags="-w -s" -o /bin/app ./cmd/product

# Step 2: Final
FROM gcr.io/distroless/static-debian12:nonroot

EXPOSE 5001

# Copy configuration
COPY --from=builder /app/cmd/product/config.yml /config.yml
COPY --from=builder /bin/app /app

ENTRYPOINT ["/app"]