# Step 1: Builder
FROM golang:1.22-alpine3.19 AS builder

WORKDIR /app

RUN apk add --no-cache git ca-certificates tzdata

# Cache dependencies
COPY go.mod go.sum ./
RUN go mod download

# Build application
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -ldflags="-w -s" -o /bin/app ./cmd/web

# Step 2: Final
FROM gcr.io/distroless/static-debian12:nonroot

WORKDIR /app

EXPOSE 8888

# Copy static assets and binary
COPY --from=builder /app/cmd/web/app ./app
COPY --from=builder /bin/app ./web-service

ENTRYPOINT ["./web-service"]