FROM gcr.io/distroless/static-debian12:nonroot

WORKDIR /app

EXPOSE 8888

# Copy static assets and the pre-built binary directly from the host workspace
COPY ./cmd/web/app ./app
COPY ./bin/web ./web-service

ENTRYPOINT ["./web-service"]