apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coffeeshop-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/T2Dzung/coffee-shop.git
    targetRevision: feat/k3s-ha
    path: infrastructure/k8s/apps/coffeeshop/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: coffeeshop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
