apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  name: tempo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://grafana-community.github.io/helm-charts
      chart: tempo
      targetRevision: 2.2.3
      helm:
        valueFiles:
          - $values/infrastructure/k8s/environments/dev/gitops/addons/tempo/values.yaml
    - repoURL: https://github.com/T2Dzung/coffee-shop.git
      targetRevision: feat/k3s-ha
      ref: values
      path: infrastructure/k8s/environments/dev/gitops/addons/observability-policies
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
