---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - platform.t2dzung.github.io
  resources:
  - coffeeshopservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - platform.t2dzung.github.io
  resources:
  - coffeeshopservices/status
  verbs:
  - get
  - patch
