apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- hpa-proxy.yaml
- hpa-product.yaml

images:
- name: go-coffeeshop-barista
  newName: 423623841278.dkr.ecr.ap-southeast-1.amazonaws.com/go-coffeeshop-barista
  newTag: 28f1dc16b80dd063617780e3281fc56b300ed83f
- name: go-coffeeshop-counter
  newName: 423623841278.dkr.ecr.ap-southeast-1.amazonaws.com/go-coffeeshop-counter
  newTag: 28f1dc16b80dd063617780e3281fc56b300ed83f
- name: go-coffeeshop-kitchen
  newName: 423623841278.dkr.ecr.ap-southeast-1.amazonaws.com/go-coffeeshop-kitchen
  newTag: 28f1dc16b80dd063617780e3281fc56b300ed83f
- name: go-coffeeshop-product
  newName: 423623841278.dkr.ecr.ap-southeast-1.amazonaws.com/go-coffeeshop-product
  newTag: 28f1dc16b80dd063617780e3281fc56b300ed83f
- name: go-coffeeshop-proxy
  newName: 423623841278.dkr.ecr.ap-southeast-1.amazonaws.com/go-coffeeshop-proxy
  newTag: 28f1dc16b80dd063617780e3281fc56b300ed83f
- name: go-coffeeshop-web
  newName: 423623841278.dkr.ecr.ap-southeast-1.amazonaws.com/go-coffeeshop-web
  newTag: 28f1dc16b80dd063617780e3281fc56b300ed83f

patches:
- patch: |-
    - op: remove
      path: /spec/replicas
  target:
    kind: Deployment
    name: proxy
- patch: |-
    - op: remove
      path: /spec/replicas
  target:
    kind: Deployment
    name: product
