apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- configmap.yaml
- postgres.yaml
- hpa-proxy.yaml
- hpa-product.yaml

images:
- digest: sha256:4cbb6110e714028731dd3b3120305511fb1ff2d84a29735357fc550dab99c676
  name: go-coffeeshop-barista
  newName: 423623841278.dkr.ecr.ap-southeast-1.amazonaws.com/go-coffeeshop-barista
- digest: sha256:f5b134a8a62905129347ee36e12a922380580f6c84de11218b752d195f9b16d4
  name: go-coffeeshop-counter
  newName: 423623841278.dkr.ecr.ap-southeast-1.amazonaws.com/go-coffeeshop-counter
- digest: sha256:bc55dc93a4f69fcda56eea75ed88543ca9085b63dd84c613169b35a171021adf
  name: go-coffeeshop-kitchen
  newName: 423623841278.dkr.ecr.ap-southeast-1.amazonaws.com/go-coffeeshop-kitchen
- digest: sha256:03e7e015e96abe245bbd4c7c2fb60f77273d93fda6dcb185f96bbe7217f3b27a
  name: go-coffeeshop-product
  newName: 423623841278.dkr.ecr.ap-southeast-1.amazonaws.com/go-coffeeshop-product
- digest: sha256:32186b4cae7582aeb904ba5a6291aa8ae0e975d6a720408d7cb7c3d4d405d7ff
  name: go-coffeeshop-proxy
  newName: 423623841278.dkr.ecr.ap-southeast-1.amazonaws.com/go-coffeeshop-proxy
- digest: sha256:c74e05d07260a1678f434b3a9e0b8334f717d0a328ae460a7fa0245d73a4d7da
  name: go-coffeeshop-web
  newName: 423623841278.dkr.ecr.ap-southeast-1.amazonaws.com/go-coffeeshop-web

patches:
- patch: |-
    - op: remove
      path: /spec/replicas
  target:
    kind: Deployment
    name: proxy
- patch: |-
    - op: remove
      path: /spec/replicas
  target:
    kind: Deployment
    name: product
