apiVersion: guard.platform.t2dzung.github.io/v1alpha1
kind: OwnershipAudit
metadata:
  name: rabbitmq-certificate-ownership
  namespace: rabbitmq-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: platform-ownership-guard
    app.kubernetes.io/managed-by: kustomize
spec:
  detectors:
    - StaleOwnerReference
  targetRules:
    - apiGroup: cert-manager.io
      version: v1
      kind: CertificateRequest
  resyncInterval: 10m
