---
# ==============================================================================
# Default variables for longhorn_prereqs role
# ==============================================================================
longhorn_prereqs_data_volume_enabled: true
longhorn_prereqs_data_volume_size: 30
longhorn_prereqs_data_volume_type: "gp3"
longhorn_prereqs_data_device_name: "/dev/sdf"
