apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: coffeeshop

resources:
- ../../base
- database-bootstrap-job.yaml
- migration-job.yaml
- configmap.yaml
- ingress.yaml

# Pinned immutable ECR digests for PROD CoffeeShop release set
# Updated automatically by GitHub Actions workflows
images:
- digest: sha256:888e5b0428e1f4975c781d6e62ffdc958019fe9fff7ea4747ebd999178c969aa
  name: go-coffeeshop-barista
  newName: 694637278772.dkr.ecr.ap-southeast-1.amazonaws.com/go-coffeeshop-barista
- digest: sha256:dfd54412149ae6aad35a481383c3b660477f75c252d05a670dd386836909aef5
  name: go-coffeeshop-counter
  newName: 694637278772.dkr.ecr.ap-southeast-1.amazonaws.com/go-coffeeshop-counter
- digest: sha256:0644fc8ef0a179fb8844d1c5bc697cbc169eb68a1dff08cd8cef9bce993180d4
  name: go-coffeeshop-kitchen
  newName: 694637278772.dkr.ecr.ap-southeast-1.amazonaws.com/go-coffeeshop-kitchen
- digest: sha256:bbe20bc8d2776ec0d0cb97a7588d152c3c413372848f104953ed8bda73d9e658
  name: go-coffeeshop-migrate
  newName: 694637278772.dkr.ecr.ap-southeast-1.amazonaws.com/go-coffeeshop-migrate
- digest: sha256:4df4baf126f29e89b4bda7b93b7509d62c8ab55c76a048f9bbff7383ede6e7d4
  name: go-coffeeshop-product
  newName: 694637278772.dkr.ecr.ap-southeast-1.amazonaws.com/go-coffeeshop-product
- digest: sha256:1f28e1145d235fdda3fbd949b4950c71effefb601116653c78e030816b031a04
  name: go-coffeeshop-proxy
  newName: 694637278772.dkr.ecr.ap-southeast-1.amazonaws.com/go-coffeeshop-proxy
- digest: sha256:581e209ef5971ebee143650eb5c92da90f4ab13bd25ff3bb8ecf71c7d46cd209
  name: go-coffeeshop-web
  newName: 694637278772.dkr.ecr.ap-southeast-1.amazonaws.com/go-coffeeshop-web

patches:
- patch: |-
    - op: add
      path: /metadata/annotations
      value:
        alb.ingress.kubernetes.io/healthcheck-path: /healthz
  target:
    version: v1
    kind: Service
    name: proxy
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi
  target:
    group: apps
    kind: Deployment
    name: (web|proxy|product|counter|barista|kitchen)
    version: v1
