---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - guard.platform.t2dzung.github.io
  resources:
  - ownershipaudits
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - guard.platform.t2dzung.github.io
  resources:
  - ownershipaudits/status
  verbs:
  - get
  - patch
  - update
