- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install HAProxy
  ansible.builtin.apt:
    name: haproxy
    state: present

- name: Configure HAProxy
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'
    validate: haproxy -c -f %s
  notify: Haproxy_lb reload

- name: Ensure HAProxy is started and enabled
  ansible.builtin.systemd:
    name: haproxy
    state: started
    enabled: true
