apiVersion: apps/v1
kind: Deployment
metadata:
  name: kitchen
  namespace: coffeeshop
  labels:
    app: kitchen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kitchen
  template:
    metadata:
      labels:
        app: kitchen
    spec:
      containers:
        - name: kitchen
          image: 423623841278.dkr.ecr.ap-southeast-1.amazonaws.com/go-coffeeshop-kitchen:9de6d85f9541b747b716c9154b48474f7d4885f7
          imagePullPolicy: IfNotPresent
          env:
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: coffeeshop-config
                  key: APP_NAME_KITCHEN
            - name: IN_DOCKER
              valueFrom:
                configMapKeyRef:
                  name: coffeeshop-config
                  key: IN_DOCKER
            - name: PG_URL
              valueFrom:
                secretKeyRef:
                  name: coffeeshop-secret
                  key: PG_URL
            - name: PG_DSN_URL
              valueFrom:
                secretKeyRef:
                  name: coffeeshop-secret
                  key: PG_DSN_URL
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: coffeeshop-secret
                  key: RABBITMQ_URL
