apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  namespace: coffeeshop
  labels:
    app: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: 423623841278.dkr.ecr.ap-southeast-1.amazonaws.com/go-coffeeshop-product:fc5b71320acf152022a8e3d8f43fb5314aeaece9
          imagePullPolicy: IfNotPresent
          env:
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: coffeeshop-config
                  key: APP_NAME_PRODUCT
          ports:
            - containerPort: 5001
              name: grpc

---
apiVersion: v1
kind: Service
metadata:
  name: product
  namespace: coffeeshop
spec:
  ports:
    - port: 5001
      targetPort: 5001
  selector:
    app: product
