apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - coffeeshop-namespace.yaml
  - configmap.yaml
  - postgres.yaml
  - barista.yaml
  - counter.yaml
  - kitchen.yaml
  - product.yaml
  - proxy.yaml
  - web.yaml
