apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  namespace: coffeeshop
  labels:
    app: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
        - name: proxy
          image: 423623841278.dkr.ecr.ap-southeast-1.amazonaws.com/go-coffeeshop-proxy:bef39cfbbc4badb56ff0c62168c778d79f4dc8a6
          imagePullPolicy: IfNotPresent
          env:
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: coffeeshop-config
                  key: APP_NAME_PROXY
            - name: GRPC_PRODUCT_HOST
              valueFrom:
                configMapKeyRef:
                  name: coffeeshop-config
                  key: GRPC_PRODUCT_HOST
            - name: GRPC_PRODUCT_PORT
              valueFrom:
                configMapKeyRef:
                  name: coffeeshop-config
                  key: GRPC_PRODUCT_PORT
            - name: GRPC_COUNTER_HOST
              valueFrom:
                configMapKeyRef:
                  name: coffeeshop-config
                  key: GRPC_COUNTER_HOST
            - name: GRPC_COUNTER_PORT
              valueFrom:
                configMapKeyRef:
                  name: coffeeshop-config
                  key: GRPC_COUNTER_PORT
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: coffeeshop-config
                  key: OTEL_EXPORTER_OTLP_ENDPOINT
            - name: OTEL_TRACES_SAMPLER
              valueFrom:
                configMapKeyRef:
                  name: coffeeshop-config
                  key: OTEL_TRACES_SAMPLER
            - name: OTEL_TRACES_SAMPLER_ARG
              valueFrom:
                configMapKeyRef:
                  name: coffeeshop-config
                  key: OTEL_TRACES_SAMPLER_ARG
            - name: OTEL_RESOURCE_ATTRIBUTES
              valueFrom:
                configMapKeyRef:
                  name: coffeeshop-config
                  key: OTEL_RESOURCE_ATTRIBUTES
          ports:
            - containerPort: 5000
              name: proxy-port
          resources:
            requests:
              cpu: 60m
              memory: 32Mi
            limits:
              cpu: 150m
              memory: 64Mi
          readinessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: coffeeshop
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: proxy
