apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../k8s/apps/coffeeshop/overlays/iximiuz-orders
# Excludes the shared namespace containing operator-managed database resources.
patches:
  - target:
      kind: Namespace
    patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: unused
      $patch: delete
