apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - storage/storageclass-gp3.yaml
  - external-secrets/cluster-secret-store.yaml
  - external-secrets/external-secret.yaml
  - external-secrets/rabbitmq-external-secret.yaml
  - rabbitmq/rabbitmq-cluster.yaml
  - rabbitmq/pdb.yaml
  - rabbitmq/networkpolicy.yaml
