//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationReference) DeepCopyInto(out *ApplicationReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationReference.
func (in *ApplicationReference) DeepCopy() *ApplicationReference {
	if in == nil {
		return nil
	}
	out := new(ApplicationReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditSummary) DeepCopyInto(out *AuditSummary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditSummary.
func (in *AuditSummary) DeepCopy() *AuditSummary {
	if in == nil {
		return nil
	}
	out := new(AuditSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OwnershipAudit) DeepCopyInto(out *OwnershipAudit) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OwnershipAudit.
func (in *OwnershipAudit) DeepCopy() *OwnershipAudit {
	if in == nil {
		return nil
	}
	out := new(OwnershipAudit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OwnershipAudit) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OwnershipAuditList) DeepCopyInto(out *OwnershipAuditList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OwnershipAudit, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OwnershipAuditList.
func (in *OwnershipAuditList) DeepCopy() *OwnershipAuditList {
	if in == nil {
		return nil
	}
	out := new(OwnershipAuditList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OwnershipAuditList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OwnershipAuditSpec) DeepCopyInto(out *OwnershipAuditSpec) {
	*out = *in
	if in.ApplicationRefs != nil {
		in, out := &in.ApplicationRefs, &out.ApplicationRefs
		*out = make([]ApplicationReference, len(*in))
		copy(*out, *in)
	}
	if in.Detectors != nil {
		in, out := &in.Detectors, &out.Detectors
		*out = make([]DetectorType, len(*in))
		copy(*out, *in)
	}
	if in.TargetRules != nil {
		in, out := &in.TargetRules, &out.TargetRules
		*out = make([]TargetRule, len(*in))
		copy(*out, *in)
	}
	out.ResyncInterval = in.ResyncInterval
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OwnershipAuditSpec.
func (in *OwnershipAuditSpec) DeepCopy() *OwnershipAuditSpec {
	if in == nil {
		return nil
	}
	out := new(OwnershipAuditSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OwnershipAuditStatus) DeepCopyInto(out *OwnershipAuditStatus) {
	*out = *in
	if in.LastCompletedScanTime != nil {
		in, out := &in.LastCompletedScanTime, &out.LastCompletedScanTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Summary = in.Summary
	if in.Findings != nil {
		in, out := &in.Findings, &out.Findings
		*out = make([]OwnershipFinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OwnershipAuditStatus.
func (in *OwnershipAuditStatus) DeepCopy() *OwnershipAuditStatus {
	if in == nil {
		return nil
	}
	out := new(OwnershipAuditStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OwnershipFinding) DeepCopyInto(out *OwnershipFinding) {
	*out = *in
	out.Target = in.Target
	if in.MissingEvidence != nil {
		in, out := &in.MissingEvidence, &out.MissingEvidence
		*out = make([]MissingEvidence, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OwnershipFinding.
func (in *OwnershipFinding) DeepCopy() *OwnershipFinding {
	if in == nil {
		return nil
	}
	out := new(OwnershipFinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceReference) DeepCopyInto(out *ResourceReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceReference.
func (in *ResourceReference) DeepCopy() *ResourceReference {
	if in == nil {
		return nil
	}
	out := new(ResourceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetRule) DeepCopyInto(out *TargetRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetRule.
func (in *TargetRule) DeepCopy() *TargetRule {
	if in == nil {
		return nil
	}
	out := new(TargetRule)
	in.DeepCopyInto(out)
	return out
}
