apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: coffeeshop-rabbitmq
  namespace: coffeeshop
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: 3
  service:
    type: ClusterIP
  persistence:
    storageClassName: gp3
    storage: 5Gi
  resources:
    requests:
      cpu: "250m"
      memory: "1Gi"
    limits:
      cpu: "500m"
      memory: "1Gi"
  secretBackend:
    externalSecret:
      name: coffeeshop-rabbitmq-default-user
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - coffeeshop-rabbitmq
          topologyKey: kubernetes.io/hostname
